name: ThePlugin
main: net.kiwz.ThePlugin.ThePlugin
version: 1.00
author: Kiwz

depend: []
softdepend: [dynmap]
loadbefore: []

commands:
  entity:
    description: a = animals, m = monsters, d = drops
    aliases: [e]
    permission: ThePlugin.entity
    permission-message: §cDu har ikke tilgang!
    usage: |
      /entity a
      /entity m
      /entity d
      /entity a <distance>
      /entity m <distance>
      /entity d <distance>
  feed:
    description: Mater
    aliases: []
    permission: ThePlugin.feed
    permission-message: §cDu har ikke tilgang!
    usage: |
      /feed
      /feed <player>
  fly:
    description: Endre flymodus
    aliases: []
    permission: ThePlugin.fly
    permission-message: §cDu har ikke tilgang!
    usage: |
      /fly
      /fly <player>
  gm:
    description: Endre GameMode
    aliases: []
    permission: ThePlugin.gm
    permission-message: §cDu har ikke tilgang!
    usage: |
      /gm
      /gm <player>
  heal:
    description: Sett til full helse
    aliases: []
    permission: ThePlugin.heal
    permission-message: §cDu har ikke tilgang!
    usage: |
      /heal
      /heal <player>
  help:
    description: Viser deg hjelpe menyen
    aliases: [hjelp]
    permission: ThePlugin.help
    permission-message: §cDu har ikke tilgang!
    usage: |
      /help
      /help <side-nummer>
      /help <emne>
      /help <emne> <side-nummer>
  home:
    description: Teleporterer deg hjem
    aliases: [hjem, h]
    permission: ThePlugin.home
    permission-message: §cDu har ikke tilgang!
    usage: /home
  ignore:
    description: Du slipper mas fra spesifiserte spillere
    aliases: [i, ignorer, c, chat]
    permission: ThePlugin.ignore
    permission-message: §cDu har ikke tilgang!
    usage: |
      /ignore
      /ignore <spiller-navn>
  sethome:
    description: Setter ditt hjem der du står
    aliases: [setthjem, sh]
    permission: ThePlugin.sethome
    permission-message: §cDu har ikke tilgang!
    usage: /homeset
  list:
    description: Hvem er online
    aliases: [who, online]
    permission: ThePlugin.list
    permission-message: §cDu har ikke tilgang!
    usage: /list
  minne:
    description: Minne bruk
    aliases: [mem]
    permission: ThePlugin.minne
    permission-message: §cDu har ikke tilgang!
    usage: /mem
  mute:
    description: Nekter en spiller i å chatte
    aliases: []
    permission: ThePlugin.mute
    permission-message: §cDu har ikke tilgang!
    usage: |
      /mute <player>
      /mute list
  unmute:
    description: Nekter en spiller i å chatte
    aliases: []
    permission: ThePlugin.unmute
    permission-message: §cDu har ikke tilgang!
    usage: |
      /unmute <player>
      /unmute all
  oi:
    description: Åpner inventaret til en spiller
    aliases: []
    permission: ThePlugin.openinv
    permission-message: §cDu har ikke tilgang!
    usage: /openinv <player>
  plass:
    description: Plass kommandoer
    aliases: [p]
    permission: ThePlugin.plass
    permission-message: §cDu har ikke tilgang!
    usage: /plass
  rules:
    description: Viser deg våres regler
    aliases: [regler]
    permission: ThePlugin.rules
    permission-message: §cDu har ikke tilgang!
    usage: /regler
  spawn:
    description: Teleporterer deg til spawn
    aliases: [s]
    permission: ThePlugin.spawn
    permission-message: §cDu har ikke tilgang!
    usage: /spawn [verden]
  setspawn:
    description: Setter ny spawn
    aliases: []
    permission: ThePlugin.setspawn
    permission-message: §cDu har ikke tilgang!
    usage: /setspawn
  tell:
    description: Skriv privat melding
    aliases: [msg, m]
    permission: ThePlugin.tell
    permission-message: §cDu har ikke tilgang!
    usage: /tell <player>
  tid:
    description: Sett din egen tid
    aliases: []
    permission: ThePlugin.tid
    permission-message: §cDu har ikke tilgang!
    usage: |
      /tid dag
      /tid natt
      /tid server
  tp:
    description: Teleportering
    aliases: [t]
    permission: ThePlugin.tp
    permission-message: §cDu har ikke tilgang!
    usage: |
      /tp <player>
      /tp <x y z>
      /tp <player player>
      /tp <player x y z>
  ticks:
    description: Tiks pr sekund (skal være 20)
    aliases: [lag, tick]
    permission: ThePlugin.ticks
    permission-message: §cDu har ikke tilgang!
    usage: |
      /ticks
      /ticks <seconds>
  whois:
    description: Spiller info
    aliases: []
    permission: ThePlugin.whois
    permission-message: §cDu har ikke tilgang!
    usage: /whois <player>
  world:
    description: World spesifikke kommandoer
    aliases: [w]
    permission: ThePlugin.world
    permission-message: §cDu har ikke tilgang!
    usage: /world
  test:
    description: IKKE RØR!!!
    aliases: []
    permission: ThePlugin.test
    permission-message: §cDu har ikke tilgang!
    usage: /test

permissions:
  ThePlugin.help:
    default: true
  ThePlugin.home:
    default: true
  ThePlugin.ignore:
    default: true
  ThePlugin.list:
    default: true
  ThePlugin.minne:
    default: true
  ThePlugin.plass:
    default: true
  ThePlugin.rules:
    default: true
  ThePlugin.sethome:
    default: true
  ThePlugin.spawn:
    default: true
  ThePlugin.tell:
    default: true
  ThePlugin.tid:
    default: true
  ThePlugin.ticks:
    default: true
  bukkit.command.kill:
    default: op
  bukkit.command.me:
    default: op