name: ThePlugin
main: net.kiwz.ThePlugin.ThePlugin
version: 1.00
author: Kiwz

depend: []
softdepend: [dynmap]
loadbefore: []

commands:
  entity:
    description: a = animals, m = monsters, d = drops
    aliases: [e]
    permission: ThePlugin.entity
    permission-message: §cDu har ikke tilgang!
    usage: |
      /entity a
      /entity m
      /entity d
      /entity a <distance>
      /entity m <distance>
      /entity d <distance>
  fly:
    description: Endre flymodus
    aliases: []
    permission: ThePlugin.fly
    permission-message: §cDu har ikke tilgang!
    usage: |
      /fly
      /fly <spiller-navn>
  gm:
    description: Endre GameMode
    aliases: []
    permission: ThePlugin.gm
    permission-message: §cDu har ikke tilgang!
    usage: |
      /gm
      /gm <spiller-navn>
  heal:
    description: Sett til full helse
    aliases: []
    permission: ThePlugin.heal
    permission-message: §cDu har ikke tilgang!
    usage: |
      /heal
      /heal <spiller-navn>
  hjelp:
    description: Viser deg hjelpe menyen
    aliases: [help]
    permission: ThePlugin.hjelp
    permission-message: §cDu har ikke tilgang!
    usage: |
      /hjelp
      /hjelp <side-nummer>
      /hjelp <emne>
      /hjelp <emne> <side-nummer>
  hjem:
    description: Teleporterer deg hjem
    aliases: [h, home]
    permission: ThePlugin.hjem
    permission-message: §cDu har ikke tilgang!
    usage: /hjem
  ignorer:
    description: Du slipper mas fra spesifiserte spillere
    aliases: [ignore, i, chat, c]
    permission: ThePlugin.ignorer
    permission-message: §cDu har ikke tilgang!
    usage: |
      /ignorer
      /ignorer <spiller-navn>
  setthjem:
    description: Setter ditt hjem der du står
    aliases: [sethjem, sethome, sh]
    permission: ThePlugin.setthjem
    permission-message: §cDu har ikke tilgang!
    usage: /sethjem
  online:
    description: Hvem er online
    aliases: [who, list]
    permission: ThePlugin.online
    permission-message: §cDu har ikke tilgang!
    usage: /online
  minne:
    description: Minne-bruk
    aliases: [mem]
    permission: ThePlugin.minne
    permission-message: §cDu har ikke tilgang!
    usage: /minne
  mute:
    description: Nekter en spiller i å chatte
    aliases: []
    permission: ThePlugin.mute
    permission-message: §cDu har ikke tilgang!
    usage: |
      /mute
      /mute <spiller-navn>
  unmute:
    description: Spilleren kan chatte igjen
    aliases: []
    permission: ThePlugin.unmute
    permission-message: §cDu har ikke tilgang!
    usage: |
      /unmute <spiller-navn>
      /unmute all
  oe:
    description: Åpner enderchesten til en spiller
    aliases: [openender]
    permission: ThePlugin.oe
    permission-message: §cDu har ikke tilgang!
    usage: /openinv <spiller-navn>
  oi:
    description: Åpner inventaret til en spiller
    aliases: [openinv]
    permission: ThePlugin.oi
    permission-message: §cDu har ikke tilgang!
    usage: /openinv <spiller-navn>
  plass:
    description: Plass kommandoer
    aliases: [p]
    permission: ThePlugin.plass
    permission-message: §cDu har ikke tilgang!
    usage: /plass
  pvp:
    description: Deaktiverer pvp for deg
    aliases: [worker]
    permission: ThePlugin.pvp
    permission-message: §cDu har ikke tilgang!
    usage: /pvp
  spy:
    description: Skru av/på mottak av ALLE private meldinger
    aliases: [spymsg]
    permission: ThePlugin.spy
    permission-message: §cDu har ikke tilgang!
    usage: /spy
  svar:
    description: Skriv privat melding tilbake
    aliases: [replay, r]
    permission: ThePlugin.svar
    permission-message: §cDu har ikke tilgang!
    usage: /svar
  regler:
    description: Viser deg våres regler
    aliases: [rules]
    permission: ThePlugin.regler
    permission-message: §cDu har ikke tilgang!
    usage: /regler
  spawn:
    description: Teleporterer deg til spawn
    aliases: [s]
    permission: ThePlugin.spawn
    permission-message: §cDu har ikke tilgang!
    usage: /spawn [verden]
  setspawn:
    description: Setter ny spawn
    aliases: []
    permission: ThePlugin.setspawn
    permission-message: §cDu har ikke tilgang!
    usage: /setspawn
  melde:
    description: Skriv privat melding
    aliases: [tell, msg, m, whisper]
    permission: ThePlugin.melde
    permission-message: §cDu har ikke tilgang!
    usage: /melde <spiller-navn>
  tid:
    description: Sett din egen tid
    aliases: []
    permission: ThePlugin.tid
    permission-message: §cDu har ikke tilgang!
    usage: |
      /tid dag
      /tid natt
      /tid server
  tp:
    description: Teleportering
    aliases: []
    permission: ThePlugin.tp
    permission-message: §cDu har ikke tilgang!
    usage: |
      /tp <spiller-navn>
      /tp <x> <y> <z>
      /tp <spiller-navn> <spiller-navn>
  tpa:
    description: Akseptere en teleportering
    aliases: []
    permission: ThePlugin.tpa
    permission-message: §cDu har ikke tilgang!
    usage: /tpa
  tpchunk:
    description: Teleportering til angitt chunk
    aliases: [chunk]
    permission: ThePlugin.tpchunk
    permission-message: §cDu har ikke tilgang!
    usage: /tpchunk <world> <Chunk-x> <y> <Chunk-z>
  ticks:
    description: Tiks pr sekund (skal være 20)
    aliases: [lag, tick]
    permission: ThePlugin.ticks
    permission-message: §cDu har ikke tilgang!
    usage: |
      /ticks
      /ticks <sekunder>
  hvem:
    description: Spiller info
    aliases: [whois, where]
    permission: ThePlugin.hvem
    permission-message: §cDu har ikke tilgang!
    usage: /hvem <spiller-navn>
  world:
    description: World spesifikke kommandoer
    aliases: [w]
    permission: ThePlugin.world
    permission-message: §cDu har ikke tilgang!
    usage: /world
  test:
    description: IKKE RØR!!!
    aliases: []
    permission: ThePlugin.test
    permission-message: §cDu har ikke tilgang!
    usage: /test

permissions:
  ThePlugin.hjelp:
    default: true
  ThePlugin.hjem:
    default: true
  ThePlugin.ignorer:
    default: true
  ThePlugin.online:
    default: true
  ThePlugin.minne:
    default: true
  ThePlugin.plass:
    default: true
  ThePlugin.svar:
    default: true
  ThePlugin.regler:
    default: true
  ThePlugin.setthjem:
    default: true
  ThePlugin.spawn:
    default: true
  ThePlugin.melde:
    default: true
  ThePlugin.tid:
    default: true
  ThePlugin.ticks:
    default: true
  ThePlugin.tp:
    default: true
  ThePlugin.tpa:
    default: true
  ThePlugin.hvem:
    default: true
  bukkit.command.kill:
    default: op
  bukkit.command.me:
    default: op