name: ThePlugin
main: net.kiwz.ThePlugin.ThePlugin
version: 1.00
author: Kiwz

commands:
  entity:
    description: a = animals, m = monsters, d = drops
    aliases: [e]
    permission: ThePlugin.entity
    permission-message: §cDu har ikke tilgang!
    usage: |
      /entity a
      /entity m
      /entity d
      /entity a <distance>
      /entity m <distance>
      /entity d <distance>
  feed:
    description: Mater
    aliases: []
    permission: ThePlugin.feed
    permission-message: §cDu har ikke tilgang!
    usage: |
      /feed
      /feed <player>
  fly:
    description: Endre flymodus
    aliases: []
    permission: ThePlugin.fly
    permission-message: §cDu har ikke tilgang!
    usage: |
      /fly
      /fly <player>
  gm:
    description: Endre GameMode
    aliases: []
    permission: ThePlugin.gm
    permission-message: §cDu har ikke tilgang!
    usage: |
      /gm
      /gm <player>
  heal:
    description: Sett til full helse
    aliases: []
    permission: ThePlugin.heal
    permission-message: §cDu har ikke tilgang!
    usage: |
      /heal
      /heal <player>
  hjelp:
    description: Viser deg hjelpe menyen
    aliases: [help]
    permission: ThePlugin.hjelp
    permission-message: §cDu har ikke tilgang!
    usage: |
      /hjelp
      /hjelp <side-nummer>
      /hjelp <emne>
      /hjelp <emne> <side-nummer>
  home:
    description: Teleporterer deg hjem
    aliases: [hjem, h]
    permission: ThePlugin.home
    permission-message: §cDu har ikke tilgang!
    usage: /home
  sethome:
    description: Setter ditt hjem der du står
    aliases: [setthjem, sh]
    permission: ThePlugin.sethome
    permission-message: §cDu har ikke tilgang!
    usage: /homeset
  item:
    description: Gi item til deg eller en annen
    aliases: [i]
    permission: ThePlugin.item
    permission-message: §cDu har ikke tilgang!
    usage: |
      /item <item>
      /item <amount> <item>
      /item <amount> <item> <data>
      /item <player> <item>
      /item <player> <amount> <item>
      /item <player> <amount> <item> <data>
  minne:
    description: Minne bruk
    aliases: [mem]
    permission: ThePlugin.minne
    permission-message: §cDu har ikke tilgang!
    usage: /mem
  mute:
    description: Nekter en spiller i å chatte
    aliases: []
    permission: ThePlugin.mute
    permission-message: §cDu har ikke tilgang!
    usage: |
      /mute <player>
      /mute list
  unmute:
    description: Nekter en spiller i å chatte
    aliases: []
    permission: ThePlugin.unmute
    permission-message: §cDu har ikke tilgang!
    usage: |
      /unmute <player>
      /unmute all
  oi:
    description: Åpner inventaret til en spiller
    aliases: []
    permission: ThePlugin.openinv
    permission-message: §cDu har ikke tilgang!
    usage: /openinv <player>
  plass:
    description: Plass kommandoer
    aliases: [p]
    permission: ThePlugin.plass
    permission-message: §cDu har ikke tilgang!
    usage: /plass
  spawn:
    description: Teleporterer deg til spawn
    aliases: [s]
    permission: ThePlugin.spawn
    permission-message: §cDu har ikke tilgang!
    usage: /spawn [verden]
  setspawn:
    description: Setter ny spawn
    aliases: []
    permission: ThePlugin.setspawn
    permission-message: §cDu har ikke tilgang!
    usage: /setspawn
  tid:
    description: Sett din egen tid
    aliases: []
    permission: ThePlugin.tid
    permission-message: §cDu har ikke tilgang!
    usage: |
      /tid dag
      /tid natt
      /tid server
  tp:
    description: Teleportering
    aliases: []
    permission: ThePlugin.tp
    permission-message: §cDu har ikke tilgang!
    usage: |
      /tp <player>
      /tp <x y z>
      /tp <player player>
      /tp <player x y z>
  tps:
    description: Tiks pr sekund (skal være 20)
    aliases: []
    permission: ThePlugin.tps
    permission-message: §cDu har ikke tilgang!
    usage: |
      /tps
      /tps <seconds>
  who:
    description: Hvem er online
    aliases: [list, online]
    permission: ThePlugin.who
    permission-message: §cDu har ikke tilgang!
    usage: /who
  whois:
    description: Spiller info
    aliases: []
    permission: ThePlugin.whois
    permission-message: §cDu har ikke tilgang!
    usage: /whois <player>
  world:
    description: World spesifikke kommandoer
    aliases: [w]
    permission: ThePlugin.world
    permission-message: §cDu har ikke tilgang!
    usage: /world
  test:
    description: IKKE RØR!!!
    aliases: []
    permission: ThePlugin.test
    permission-message: §cDu har ikke tilgang!
    usage: /test

permissions:
  ThePlugin.hjelp:
    default: true
  ThePlugin.home:
    default: true
  ThePlugin.minne:
    default: true
  ThePlugin.plass:
    default: true
  ThePlugin.sethome:
    default: true
  ThePlugin.spawn:
    default: true
  ThePlugin.tid:
    default: true
  ThePlugin.tps:
    default: true
  ThePlugin.who:
    default: true
  bukkit.command.kill:
    default: op
  bukkit.command.me:
    default: op
  bukkit.command.tell:
    default: op