name: ThePlugin
main: net.kiwz.ThePlugin.ThePlugin
version: 0.01
author: Kiwz

commands:
  gm:
    description: Endre GameMode
    aliases: []
    permission: 
    permission-message: Du har ikke tilgang!
    usage: 
  fly:
    description: Endre flymodus
    aliases: []
    permission: 
    permission-message: Du har ikke tilgang!
    usage: 
  heal:
    description: Sett til full helse
    aliases: []
    permission: 
    permission-message: Du har ikke tilgang!
    usage:
  mat:
    description: Sett til mett
    aliases: []
    permission: 
    permission-message: Du har ikke tilgang!
    usage: 
  teleport:
    description: Teleport til en annen eller til koordinater
    aliases: [tp]
    permission: 
    permission-message: Du har ikke tilgang!
    usage: 
  gi:
    description: Gi ett item til deg eller en annen
    aliases: [i, give]
    permission: 
    permission-message: Du har ikke tilgang!
    usage: 
  test:
    description: Bare en test kommando
    aliases: []
    permission: 
    permission-message: Du har ikke tilgang!
    usage: Bare en test kommando