name: ThePlugin
main: net.kiwz.ThePlugin.ThePlugin
version: 0.01
author: Kiwz

commands:
  feed:
    description: Mater
    aliases: []
    permission: ThePlugin.feed
    permission-message: §cDu har ikke tilgang!
    usage: |
      /feed
      /feed <player>
  fly:
    description: Endre flymodus
    aliases: []
    permission: ThePlugin.fly
    permission-message: §cDu har ikke tilgang!
    usage: |
      /fly
      /fly <player>
  gm:
    description: Endre GameMode
    aliases: []
    permission: ThePlugin.gm
    permission-message: §cDu har ikke tilgang!
    usage: |
      /gm
      /gm <player>
  heal:
    description: Sett til full helse
    aliases: []
    permission: ThePlugin.heal
    permission-message: §cDu har ikke tilgang!
    usage: |
      /heal
      /heal <player>
  hjelp:
    description: Viser deg hjelpe menyen
    aliases: [help]
    permission: ThePlugin.hjelp
    permission-message: §cDu har ikke tilgang!
    usage: |
      /hjelp
      /hjelp <side-nummer>
      /hjelp <emne>
      /hjelp <emne> <side-nummer>
  home:
    description: Teleporterer deg hjem
    aliases: [hjem, h]
    permission: ThePlugin.home
    permission-message: §cDu har ikke tilgang!
    usage: /home
  sethome:
    description: Setter ditt hjem der du står
    aliases: [setthjem, sh]
    permission: ThePlugin.sethome
    permission-message: §cDu har ikke tilgang!
    usage: /homeset
  item:
    description: Gi item til deg eller en annen
    aliases: [i]
    permission: ThePlugin.item
    permission-message: §cDu har ikke tilgang!
    usage: |
      /item <item>
      /item <amount> <item>
      /item <amount> <item> <data>
      /item <player> <item>
      /item <player> <amount> <item>
      /item <player> <amount> <item> <data>
  oi:
    description: Åpner inventaret til en spiller
    aliases: []
    permission: ThePlugin.openinv
    permission-message: §cDu har ikke tilgang!
    usage: /openinv <player>
  plass:
    description: Plass kommandoer
    aliases: [p]
    permission: ThePlugin.plass
    permission-message: §cDu har ikke tilgang!
    usage: /plass
  spawn:
    description: Teleporterer deg til spawn
    aliases: [s]
    permission: ThePlugin.spawn
    permission-message: §cDu har ikke tilgang!
    usage: /spawn [verden]
  setspawn:
    description: Setter ny spawn
    aliases: []
    permission: ThePlugin.setspawn
    permission-message: §cDu har ikke tilgang!
    usage: /setspawn
  tp:
    description: Teleportering
    aliases: []
    permission: ThePlugin.tp
    permission-message: §cDu har ikke tilgang!
    usage: |
      /tp <player>
      /tp <x y z>
      /tp <player player>
      /tp <player x y z>
  world:
    description: World spesifikke kommandoer
    aliases: [w]
    permission: ThePlugin.world
    permission-message: §cDu har ikke tilgang!
    usage: /world
  test:
    description: Bare en test kommando
    aliases: []
    permission: ThePlugin.test
    permission-message: §cDu har ikke tilgang!
    usage: /test

permissions:
  ThePlugin.hjelp:
    default: true
  ThePlugin.home:
    default: true
  ThePlugin.plass:
    default: true
  ThePlugin.sethome:
    default: true
  ThePlugin.spawn:
    default: true
  bukkit.command.kill:
    default: op
  bukkit.command.me:
    default: op
  bukkit.command.plugins:
    default: op
  bukkit.command.tell:
    default: op
  bukkit.command.version:
    default: op