name: ThePlugin
main: net.kiwz.ThePlugin.ThePlugin
version: 1.00
author: Kiwz

depend: []
softdepend: [dynmap]
loadbefore: []

commands:
  entity:
    description: a = animals, m = monsters, d = drops
    aliases: [e]
    permission: ThePlugin.entity
    permission-message: §cDu har ikke tilgang!
    usage: |
      /entity a
      /entity m
      /entity d
      /entity a <distance>
      /entity m <distance>
      /entity d <distance>
  feed:
    description: Mater
    aliases: []
    permission: ThePlugin.feed
    permission-message: §cDu har ikke tilgang!
    usage: |
      /feed
      /feed <player>
  fly:
    description: Endre flymodus
    aliases: []
    permission: ThePlugin.fly
    permission-message: §cDu har ikke tilgang!
    usage: |
      /fly
      /fly <player>
  gm:
    description: Endre GameMode
    aliases: []
    permission: ThePlugin.gm
    permission-message: §cDu har ikke tilgang!
    usage: |
      /gm
      /gm <player>
  heal:
    description: Sett til full helse
    aliases: []
    permission: ThePlugin.heal
    permission-message: §cDu har ikke tilgang!
    usage: |
      /heal
      /heal <player>
  hjelp:
    description: Viser deg hjelpe menyen
    aliases: [help]
    permission: ThePlugin.help
    permission-message: §cDu har ikke tilgang!
    usage: |
      /hjelp
      /hjelp <side-nummer>
      /hjelp <emne>
      /hjelp <emne> <side-nummer>
  hjem:
    description: Teleporterer deg hjem
    aliases: [h, home]
    permission: ThePlugin.home
    permission-message: §cDu har ikke tilgang!
    usage: /hjem
  ignorer:
    description: Du slipper mas fra spesifiserte spillere
    aliases: [ignore, i, chat, c]
    permission: ThePlugin.ignore
    permission-message: §cDu har ikke tilgang!
    usage: |
      /ignorer
      /ignorer <spiller-navn>
  setthjem:
    description: Setter ditt hjem der du står
    aliases: [sethjem, sethome, sh]
    permission: ThePlugin.sethome
    permission-message: §cDu har ikke tilgang!
    usage: /sethjem
  online:
    description: Hvem er online
    aliases: [who, list]
    permission: ThePlugin.list
    permission-message: §cDu har ikke tilgang!
    usage: /online
  minne:
    description: Minne bruk
    aliases: [mem]
    permission: ThePlugin.minne
    permission-message: §cDu har ikke tilgang!
    usage: /minne
  mute:
    description: Nekter en spiller i å chatte
    aliases: []
    permission: ThePlugin.mute
    permission-message: §cDu har ikke tilgang!
    usage: |
      /mute
      /mute <player>
  unmute:
    description: Spilleren kan chatte igjen
    aliases: []
    permission: ThePlugin.unmute
    permission-message: §cDu har ikke tilgang!
    usage: |
      /unmute <player>
      /unmute all
  oi:
    description: Åpner inventaret til en spiller
    aliases: [openinv]
    permission: ThePlugin.openinv
    permission-message: §cDu har ikke tilgang!
    usage: /openinv <player>
  plass:
    description: Plass kommandoer
    aliases: [p]
    permission: ThePlugin.plass
    permission-message: §cDu har ikke tilgang!
    usage: /plass
  pvp:
    description: Deaktiverer pvp for deg
    aliases: [worker]
    permission: ThePlugin.pvp
    permission-message: §cDu har ikke tilgang!
    usage: /pvp
  svar:
    description: Skriv privat melding tilbake
    aliases: [replay, r]
    permission: ThePlugin.replay
    permission-message: §cDu har ikke tilgang!
    usage: /svar
  regler:
    description: Viser deg våres regler
    aliases: [rules]
    permission: ThePlugin.rules
    permission-message: §cDu har ikke tilgang!
    usage: /regler
  spawn:
    description: Teleporterer deg til spawn
    aliases: [s]
    permission: ThePlugin.spawn
    permission-message: §cDu har ikke tilgang!
    usage: /spawn [verden]
  setspawn:
    description: Setter ny spawn
    aliases: []
    permission: ThePlugin.setspawn
    permission-message: §cDu har ikke tilgang!
    usage: /setspawn
  melde:
    description: Skriv privat melding
    aliases: [tell, msg, m, whisper]
    permission: ThePlugin.tell
    permission-message: §cDu har ikke tilgang!
    usage: /melde <player>
  tid:
    description: Sett din egen tid
    aliases: []
    permission: ThePlugin.tid
    permission-message: §cDu har ikke tilgang!
    usage: |
      /tid dag
      /tid natt
      /tid server
  tp:
    description: Teleportering
    aliases: [t]
    permission: ThePlugin.tp
    permission-message: §cDu har ikke tilgang!
    usage: |
      /tp <player>
      /tp <x y z>
      /tp <player player>
      /tp <player x y z>
  tpchunk:
    description: Teleportering til angitt chunk
    aliases: [chunk]
    permission: ThePlugin.tpchunk
    permission-message: §cDu har ikke tilgang!
    usage: /tpchunk <world> <x y z>
  ticks:
    description: Tiks pr sekund (skal være 20)
    aliases: [lag, tick]
    permission: ThePlugin.ticks
    permission-message: §cDu har ikke tilgang!
    usage: |
      /ticks
      /ticks <seconds>
  hvem:
    description: Spiller info
    aliases: [whois, where]
    permission: ThePlugin.whois
    permission-message: §cDu har ikke tilgang!
    usage: /hvem <player>
  world:
    description: World spesifikke kommandoer
    aliases: [w]
    permission: ThePlugin.world
    permission-message: §cDu har ikke tilgang!
    usage: /world
  test:
    description: IKKE RØR!!!
    aliases: []
    permission: ThePlugin.test
    permission-message: §cDu har ikke tilgang!
    usage: /test

permissions:
  ThePlugin.help:
    default: true
  ThePlugin.home:
    default: true
  ThePlugin.ignore:
    default: true
  ThePlugin.list:
    default: true
  ThePlugin.minne:
    default: true
  ThePlugin.plass:
    default: true
  ThePlugin.replay:
    default: true
  ThePlugin.rules:
    default: true
  ThePlugin.sethome:
    default: true
  ThePlugin.spawn:
    default: true
  ThePlugin.tell:
    default: true
  ThePlugin.tid:
    default: true
  ThePlugin.ticks:
    default: true
  ThePlugin.whois:
    default: true
  bukkit.command.kill:
    default: op
  bukkit.command.me:
    default: op