name: ThePlugin
main: net.kiwz.ThePlugin.ThePlugin
version: 0.01
author: Kiwz

commands:
  feed:
    description: Sett til mett
    aliases: [mat]
    permission: ThePlugin.feed
    permission-message: Du har ikke tilgang!
    usage: |
      §c/feed
      §c/feed <player>
  fly:
    description: Endre flymodus
    aliases: []
    permission: ThePlugin.fly
    permission-message: Du har ikke tilgang!
    usage: |
      §c/fly
      §c/fly <player>
  give:
    description: Gi ett item til deg eller en annen
    aliases: [i, gi]
    permission: ThePlugin.give
    permission-message: Du har ikke tilgang!
    usage: |
      §c/give <item>
      §c/give <amount> <item>
      §c/give <amount> <item> <data>
      §c/give <player> <item>
      §c/give <player> <amount> <item>
      §c/give <player> <amount> <item> <data>
  gm:
    description: Endre GameMode
    aliases: []
    permission: ThePlugin.gm
    permission-message: Du har ikke tilgang!
    usage: |
      §c/gm
      §c/gm <player>
  heal:
    description: Sett til full helse
    aliases: []
    permission: ThePlugin.heal
    permission-message: Du har ikke tilgang!
    usage: |
      §c/heal
      §c/heal <player>
  hjelp:
    description: Viser deg hjelp menyen
    aliases: []
    permission: ThePlugin.hjelp
    permission-message: Du har ikke tilgang!
    usage: |
      §c/hjelp <sideNummer>
      §c/hjelp <emne>
      §c/hjelp <emne> <sideNummer>
  openinv:
    description: Åpner inventaret til spilleren
    aliases: [oi, oinv, openi, openinventory]
    permission: ThePlugin.openinv
    permission-message: Du har ikke tilgang!
    usage: §c/openinv <player>
  teleport:
    description: Teleporter til en annen eller til koordinater
    aliases: [tp]
    permission: ThePlugin.teleport
    permission-message: Du har ikke tilgang!
    usage: |
      §c/teleport <player>
      §c/teleport <x y z>
      §c/teleport <player> <player>
      §c/teleport <player> <x y z>
  test:
    description: Bare en test kommando
    aliases: []
    permission: ThePlugin.test
    permission-message: Du har ikke tilgang!
    usage: §c/test

permissions:
  ThePlugin.hjelp:
    default: true